# Permalinks
permalink:           pretty

# Setup
title:               Datapunks
tagline:             Mission with byte
url:                 http://datapunks.github.io
# url:                 http://localhost:4000
paginate:            0
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              David Woodruff
  url:               https://www.datapunks.ca/about
  email:             david@datapunks.ca

# Custom vars
version:             3.0.0
github:
  repo:

  # Google Analytics
google_analytics: UA—118357195-1
